# Generated by Django 5.2 on 2025-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_tasks_attachment_tasks_category_tasks_external_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='participants',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='participants',
            field=models.TextField(default=1, help_text='Comma-separated list of participants'),
            preserve_default=False,
        ),
    ]
