# Generated by Django 5.2 on 2025-05-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_alter_tasks_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='taskmanager.taskgroup'),
        ),
    ]
