# Generated by Django 5.2 on 2025-05-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_tasks_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='group_tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
