# Generated by Django 5.2 on 2025-05-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0010_alter_taskgroup_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='group',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='group_tasks',
            field=models.TextField(blank=True, help_text='Comma-separated list of tasks', null=True),
        ),
    ]
